name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Execute Gradle build
      run: ./gradlew build
