name: Pipeline

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
     
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Set up SSH
        run: |
             mkdir -p $HOME/.ssh
             echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
             chmod 600 $HOME/.ssh/id_rsa
             eval "$(ssh-agent -s)"
             ssh-add $HOME/.ssh/id_rsa

      - name: Display public key
        run: |
              ssh-keygen -y -f $HOME/.ssh/id_rsa
